/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
/**
 *
 * @author minid
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbackground = new javax.swing.JPanel();
        jLabelTituloMenu = new javax.swing.JLabel();
        jLabelContornoTitulo = new javax.swing.JLabel();
        jLabelFondoITVO = new javax.swing.JLabel();
        jLabelLogoITVO = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelbackground.setBackground(new java.awt.Color(204, 204, 204));
        jPanelbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloMenu.setFont(new java.awt.Font("Belleza", 1, 48)); // NOI18N
        jLabelTituloMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloMenu.setText("MENU PRINCIPAL");
        jLabelTituloMenu.setToolTipText("");
        jPanelbackground.add(jLabelTituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, 40));

        jLabelContornoTitulo.setFont(new java.awt.Font("Belleza", 1, 49)); // NOI18N
        jLabelContornoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContornoTitulo.setText("MENU PRINCIPAL");
        jPanelbackground.add(jLabelContornoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, -1));

        jLabelFondoITVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondos/ComprobanteDomicilio (20).png"))); // NOI18N
        jPanelbackground.add(jLabelFondoITVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 130));

        jLabelLogoITVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/ComprobanteDomicilio (21).png"))); // NOI18N
        jPanelbackground.add(jLabelLogoITVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 125, 160, 200));

        btnRegistrar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setToolTipText("");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPanelbackground.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 40));

        jLabel1.setFont(new java.awt.Font("Belleza", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione una opción");
        jPanelbackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnCerrar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanelbackground.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
    btnCerrar.setBackground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
    btnCerrar.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
    VistaRegistrarConsultarEstudiante objVistaRegtrEst = new VistaRegistrarConsultarEstudiante(this);  
    objVistaRegtrEst.setVisible(true);
    this.setVisible(false);
   
    // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
    System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContornoTitulo;
    private javax.swing.JLabel jLabelFondoITVO;
    private javax.swing.JLabel jLabelLogoITVO;
    private javax.swing.JLabel jLabelTituloMenu;
    private javax.swing.JPanel jPanelbackground;
    // End of variables declaration//GEN-END:variables
}
