package vista;
import controlador.ControladorRegistrarConsultarEstudiante;

public class VistaRegistrarConsultarEstudiante extends javax.swing.JFrame {
    VistaMenuPrincipal menu;
    ControladorRegistrarConsultarEstudiante ctlRegConEst;
    
    public VistaRegistrarConsultarEstudiante(VistaMenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        this.ctlRegConEst = new ControladorRegistrarConsultarEstudiante(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabelTituloRegtrEst = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumControl = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCarrera = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();
        txtNumControl = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCarrera = new javax.swing.JComboBox<>();
        txtPromedio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(204, 204, 204));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloRegtrEst.setFont(new java.awt.Font("Belleza", 1, 36)); // NOI18N
        jLabelTituloRegtrEst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloRegtrEst.setText("REGISTRAR ESTUDIANTE");
        bgPanelConsulta.add(jLabelTituloRegtrEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, -1));

        jLabel1.setFont(new java.awt.Font("Belleza", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRAR ESTUDIANTE");
        bgPanelConsulta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabelNumControl.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelNumControl.setText("Num. Control:");
        bgPanelConsulta.add(jLabelNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabelCarrera.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelCarrera.setText("Carrera:");
        bgPanelConsulta.add(jLabelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabelPromedio.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelPromedio.setText("Promedio:");
        bgPanelConsulta.add(jLabelPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        bgPanelConsulta.add(txtNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, -1));

        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Agronomía", "Licenciatura en Biología", "Ingeniería Forestal", "Ingeniería Informática", "Ingeniería en Tecnologías de la Información y Comunicaciones", "Ingeniería en Ciencia de Datos", "Ingeniería Ambiental", "Ingeniería en Gestión Empresarial" }));
        bgPanelConsulta.add(cboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, -1));
        bgPanelConsulta.add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 250, -1));

        btnGuardar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        btnListar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 90, -1));

        btnRegresar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Control", "Nombre", "Carrera", "Promedio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
    this.guardarRegistro();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
    this.listarEstudiante();        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarMouseClicked

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumControl;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JLabel jLabelTituloRegtrEst;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumControl;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables

    private void guardarRegistro() {
    this.ctlRegConEst.registrarEstudiante(this.txtNumControl.getText(),
                this.txtNombre.getText(), 
                this.cboCarrera.getSelectedItem().toString(),
                Double.parseDouble(this.txtPromedio.getText()));
    
    this.limpiarCajas();

    }
    
    private void listarEstudiante(){
        String[] columnas = {"Num. Control", "Nombre", "Carrera","Promedio"};                      
        this.ctlRegConEst.listarEst(columnas);  
            
    }
    
    private void limpiarCajas(){
        this.txtNumControl.setText("");
        this.txtPromedio.setText("");
        this.txtNombre.setText("");                
   
   
    
    }
    
}
