package vista;
import controlador.ControladorAgregarMostrarContactos;

public class VistaInventario extends javax.swing.JFrame {
    ControladorAgregarMostrarContactos ctlAggMosContact;
    
    public static void main(String[] args) {
        VistaInventario objViewContact = new VistaInventario();
        objViewContact.setVisible(true);
    }
    
    
    public VistaInventario() {
        initComponents();
        this.ctlAggMosContact = new ControladorAgregarMostrarContactos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnMostrarInventario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabelTituloListaInventario = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabeTituloInventario = new javax.swing.JLabel();
        bgTituloInventario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(204, 204, 204));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        bgPanelConsulta.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        bgPanelConsulta.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));
        bgPanelConsulta.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, -1));

        btnGuardar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, -1));

        btnMostrarInventario.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnMostrarInventario.setText("MOSTRAR INVENTARIO");
        btnMostrarInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarInventarioMouseClicked(evt);
            }
        });
        btnMostrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInventarioActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnMostrarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 180, -1));

        tblProductos.setAutoCreateRowSorter(true);
        tblProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
        }

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 290));

        jLabelTituloListaInventario.setFont(new java.awt.Font("Belleza", 1, 24)); // NOI18N
        jLabelTituloListaInventario.setText("Lista de Inventario");
        bgPanelConsulta.add(jLabelTituloListaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));
        bgPanelConsulta.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, -1));

        jLabeTituloInventario.setBackground(new java.awt.Color(255, 255, 255));
        jLabeTituloInventario.setFont(new java.awt.Font("Belleza", 1, 48)); // NOI18N
        jLabeTituloInventario.setForeground(new java.awt.Color(255, 255, 255));
        jLabeTituloInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeTituloInventario.setText("INVENTARIO");
        bgPanelConsulta.add(jLabeTituloInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 110));

        bgTituloInventario.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout bgTituloInventarioLayout = new javax.swing.GroupLayout(bgTituloInventario);
        bgTituloInventario.setLayout(bgTituloInventarioLayout);
        bgTituloInventarioLayout.setHorizontalGroup(
            bgTituloInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        bgTituloInventarioLayout.setVerticalGroup(
            bgTituloInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        bgPanelConsulta.add(bgTituloInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
    this.guardarContacto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnMostrarInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarInventarioMouseClicked
    this.mostrarContactos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarInventarioMouseClicked

    private void btnMostrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarInventarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JPanel bgTituloInventario;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarInventario;
    private javax.swing.JLabel jLabeTituloInventario;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTituloListaInventario;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

  
    
    private void mostrarContactos(){
        String[] columnas = {"Nombre", "Telefono","Email"};
        this.ctlAggMosContact.mostrarContactos(columnas);
            
    }
    
    private void limpiarCajas(){
        this.txtNombre.setText("");
        this.txtTelefono.setText("");
        this.txtEmail.setText("");
   
   
    
    }

    private void guardarContacto() {
        this.ctlAggMosContact.agregarContacto(this.txtNombre.getText(),
        this.txtTelefono.getText(),
        this.txtEmail.getText());
        
        this.limpiarCajas();
        
    }
    
}
